### Array Multiplication

Matrix multiplication is not regular multiplication:
- use the `@` operator like ---- `A @ B`
- use the `np.matmul( A , B )`

In [30]:
import numpy as np

In [31]:
# Matrix Multiplication

# 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [32]:
C = A * B # element wise operation or Broadcasting
C

array([[ 5, 12],
       [21, 32]])

In [33]:
# 2x2 matrices
A = np.array([2, 2, 3]) # row

B = np.array([[10], [10], [10]]) # column vector


print(A.shape) # 1 x 3
print(B.shape) # 3 x 1

(3,)
(3, 1)


In [34]:
D = A @ B # Row to column --- possible
D

#E = B @ A # column to row is not
E = np.matmul(A, B)
E

array([70])

In [35]:
# Example 3

A = np.array([[2,  2,  3],
             [20, 20, 20]]) # row ---> shape = ( 2 , 3 )

B = np.array([[2, 3],
              [3, 3],
              [5, 5]]) # column vector ---> Shape ---> ( 3 , 2 )


# 2 ,3  --- 3,2 
# is matrix multiplication possible?
A @ B


#print(A.shape) # 1 x 3
#print(B.shape) # 3 x 1

array([[ 25,  27],
       [200, 220]])

### Aggregations 
- Aggregations: - data and you summarize it 
    - Sum
    - mean
    - min max
    - Standard Deviation
    - Variance
    - count
    - argmax argmin

- Aggregation along an AXIS
- `axis = 0` ===> operate on Columns --- (down the ROWs)
- `axis = 1` ===> operate on Rows ---  (across the COLUMN)

In [36]:
data1d = np.array([2, 5, 12, 6, 7, 9])

data1d.sum()
data1d.min()
data1d.max()

data1d.argmax() # 2 ===> at 2 lies the higest number of the list
data1d.argmin() # index of the smallest number

np.int64(0)

In [37]:
data = np.array([[2,  2,   3],
                 [20, 1,  20],
                 [ 3,  4,  5]])

# aggregations - using numpy array methods
data.sum() # add all the elements inside this array

data.mean() # mean ---> sum of all elements / number of elements ====> Average value of data

data.min() # smallest element
data.max() # largest element

data.std()
data.var()

data.argmax()
data.argmin()

data.size    # the number of elements 

9

In [38]:
print("Column-Wise sum (axis = 0)",data.sum(axis = 0)) # column wise means -- down the rows
print("Row-wise Wise sum (axis = 1)",data.sum(axis = 1)) # row wise means --- across the columns

# give me the mean of all the rows in the array
data.mean(axis = 1)

Column-Wise sum (axis = 0) [25  7 28]
Row-wise Wise sum (axis = 1) [ 7 41 12]


array([ 2.33333333, 13.66666667,  4.        ])

In [39]:
# ways to aggregate data in python
#PYTHON
# very insufficient

data_list = [1, 2, 3, 4, 5]
data_list2d = [[2,  2,  3], [20, 20, 20]]

sum(data)  # array([22, 22, 23])

sum(data_list)  # 15 === sum of all elements

#sum(data_list2d) # unsupported by python
# mean(data) # in python mean is not any method

min(data_list)
max(data_list)
# min(data) # 2d array - python is confused

# A python method that is used, despite of numpy
# length of the iterable or sequential
len(data_list2d)

2

### Boolean Masking - (Filtering)
- used to filter elements out
- 
- array[mask] ==== mask is a condition
- `array_name[<condition>]`

In [40]:
scores = np.array([45, 71, 88, 30, 55, 90])

# broadcasting works on arrays
scores > 50  # array([False,  True,  True, False,  True,  True])
# element wise comparison

# Boolean masking
scores[scores > 50] # whereever this condition is true


# mask is just a condition
mask = scores % 2 == 0
scores[mask]

array([88, 30, 90])

In [41]:
age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])

# i only want to pass ages >= 18
vote_age = age[age >= 18]
print(vote_age)

[24 51 23 29 33 44]


In [42]:
# np. where works with conditionals
# np.where(condition, value_if_True, value_if_False)

In [43]:
# where
age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])

voting_eligiblity = np.where(age >= 18, "Eligible", "Not-Eligible")
print(age)
print(voting_eligiblity)
print("---"*5)

zip_list = list(zip(age, voting_eligiblity))
# zip - packs two iterables of equal length together

for age, eligibility in zip(age, voting_eligiblity):
    print(f"{age} : {eligibility}")


[ 5 17 24 51 23 14  8 29 33 44 10]
['Not-Eligible' 'Not-Eligible' 'Eligible' 'Eligible' 'Eligible'
 'Not-Eligible' 'Not-Eligible' 'Eligible' 'Eligible' 'Eligible'
 'Not-Eligible']
---------------
5 : Not-Eligible
17 : Not-Eligible
24 : Eligible
51 : Eligible
23 : Eligible
14 : Not-Eligible
8 : Not-Eligible
29 : Eligible
33 : Eligible
44 : Eligible
10 : Not-Eligible


In [44]:
zip_list

[(np.int64(5), np.str_('Not-Eligible')),
 (np.int64(17), np.str_('Not-Eligible')),
 (np.int64(24), np.str_('Eligible')),
 (np.int64(51), np.str_('Eligible')),
 (np.int64(23), np.str_('Eligible')),
 (np.int64(14), np.str_('Not-Eligible')),
 (np.int64(8), np.str_('Not-Eligible')),
 (np.int64(29), np.str_('Eligible')),
 (np.int64(33), np.str_('Eligible')),
 (np.int64(44), np.str_('Eligible')),
 (np.int64(10), np.str_('Not-Eligible'))]

In [45]:
# column stack combines two arrays of equal length

age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])
voting_eligiblity = np.where(age >= 18, "Eligible", "Not-Eligible")

combined_array = np.column_stack((age, voting_eligiblity))
combined_array

array([['5', 'Not-Eligible'],
       ['17', 'Not-Eligible'],
       ['24', 'Eligible'],
       ['51', 'Eligible'],
       ['23', 'Eligible'],
       ['14', 'Not-Eligible'],
       ['8', 'Not-Eligible'],
       ['29', 'Eligible'],
       ['33', 'Eligible'],
       ['44', 'Eligible'],
       ['10', 'Not-Eligible']], dtype='<U21')

---
BONUS PART

### Nested Loops

```python

for <variable> in <iterable>:
    print(<variable>)

In [46]:
# simple loop

for i in range(5):
    print(i)

0
1
2
3
4


In [47]:
alist = [3,5,7,9]
name = "Idrees"

for variable in name:
    print(variable)

I
d
r
e
e
s


- enumerate object is a sequence
- just like zip

- just like range - range can be type casted into a list
    - others cannot

- we run for loops on them - 

In [48]:
list(range(5))

[0, 1, 2, 3, 4]

In [49]:
for i,j in enumerate(name): # is a sequence as
    print(i,j)

0 I
1 d
2 r
3 e
4 e
5 s


In [50]:
# Nested - 
for i in range(5):
    for j in range(5):
        print(i)
# execute 5 * 5 = 25 times

0
0
0
0
0
1
1
1
1
1
2
2
2
2
2
3
3
3
3
3
4
4
4
4
4


In [ ]:
array2d = [
    [2,  4, 6, 8], # row 0
    [20,40,60,80], # row 1
    [40,40,60,80], # row 1
    [90,40,60,80], # row 1
    [70,40,60,80], # row 1
] 

#print(array2d)

# nested loops are used in python
for row in array2d:
    for value in row: 
        print(value, end =" ") # does not print in the new line    
    print() # creates a new line


2 4 6 8 
20 40 60 80 
40 40 60 80 
90 40 60 80 
70 40 60 80 


In [55]:
# i and j
# i is used for row
# j used for column

for i in range(len(array2d)):
    for j in range(len(array2d[i])):
        print(f"Row {i}, col {j}  {array2d[i][j]}")

Row 0, col 0  2
Row 0, col 1  4
Row 0, col 2  6
Row 0, col 3  8
Row 1, col 0  20
Row 1, col 1  40
Row 1, col 2  60
Row 1, col 3  80
Row 2, col 0  40
Row 2, col 1  40
Row 2, col 2  60
Row 2, col 3  80
Row 3, col 0  90
Row 3, col 1  40
Row 3, col 2  60
Row 3, col 3  80
Row 4, col 0  70
Row 4, col 1  40
Row 4, col 2  60
Row 4, col 3  80


In [54]:
array2d = np.array([
    [2,  4, 6, 8], # row 0
    [20,40,60,80], # row 1
    [40,40,60,80], # row 1
    [90,40,60,80], # row 1
    [70,40,60,80], # row 1
]) 

print(array2d)

[[ 2  4  6  8]
 [20 40 60 80]
 [40 40 60 80]
 [90 40 60 80]
 [70 40 60 80]]


### Exercises


The Scenario:

- The school's database has just exported a batch of raw exam scores. You need to use NumPy to generate some sample data, inspect its structure, and automatically grade the students based on a curve.

Your Tasks:

1. The Setup: Import NumPy. To ensure the whole class gets the exact same "random" numbers, set the random seed to 42.

2. Data Generation: Use random.randint to generate a 2D array of random scores between 0 and 100. The array should represent 10 students and their scores across 3 different subjects.

3. Array Inspection: Prove you built the array correctly by printing its ndim (number of dimensions), its shape, and its total size (total number of scores).

4. Student IDs: Use arange to create a 1D array of Student IDs starting at 100 and ending at 110.

5. Perform the aggregate operation of average and find the average score of students for each subject

6. The Audit (Boolean Masking): The principal wants to know every instance where a student scored below a 50. Use boolean masking to extract and print just those failing scores from the main array.

7. Automated Grading (where): Use np.where to create a brand new "Report Card" array. If a score in the original array is less than 50, it should say "Fail". If it is 50 or above, it should say "Pass".



In [1]:
#Exercise
 
#1.
import numpy as np
np.random.seed(42)
 
#2.
results = np.random.randint(0,101, (10,3))
print("--- Results ---")
print(results)
 
#3.
print(f"\nDimensions: {results.ndim}, Shape: {results.shape}, Size: {results.size}")
 
#4.
student_ID = [x for x in range(100,111)]
 
#5.
subject_averages = results.mean(axis=0)
print(f"AverageScore:\nSubject 1: {subject_averages[0]:.0f}, Subject 2: {subject_averages[1]:.0f}, Subject 3: {subject_averages[2]:.0f}")
 
#6.
failing_scores = results[results < 50]
print("\n--- Failing Scores (< 50) ---")
print(failing_scores)
 
#7.
report_card = np.where(results < 50, "Fail", "Pass")
print("\n--- Final Report Card ---")
print(report_card)

--- Results ---
[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]

Dimensions: 2, Shape: (10, 3), Size: 30
AverageScore:
Subject 1: 50, Subject 2: 59, Subject 3: 44

--- Failing Scores (< 50) ---
[14 20 23  2 21  1 29 37  1 20 32 21 48]

--- Final Report Card ---
[['Pass' 'Pass' 'Fail']
 ['Pass' 'Pass' 'Fail']
 ['Pass' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Fail' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Fail']
 ['Fail' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Fail']]


The Scenario 2:

The semester is over. The administration has updated the grading policy: if a student fails even one subject (scores below 50), their overall status becomes "Fail". The principal needs you to generate a final report that includes Student IDs, their scores, and their final Pass/Fail status. You must combine this data into one final grid, export it, and try to apply a last-minute bonus.

Your Tasks:

(Assume you already have your results array of 10 students across 3 subjects, and your student_ID array from 100 to 109).

1. Column Extraction (2D Slicing): Using 2D slicing, extract each subject from the results array into its own 1D variable. You should end up with subject_1, subject_2, and subject_3.

2. The Strict Grading Logic (np.where): Use np.where to create a strict_status array. If a student scored below 50 in Subject 1, OR Subject 2, OR Subject 3, their status is "Fail". Otherwise, it is "Pass".

    - Hint: In standard Python you use the word or, but in NumPy, you must use the Bitwise OR operator (|).

    - Crucial Rule: When combining multiple conditions in NumPy, you must wrap each individual condition in parentheses! (condition 1) | (condition 2)

3. The Big Merge (column_stack): The principal wants all data side-by-side. Use np.column_stack to merge the student_ID array, the original 2D results array, and your new strict_status array into one single 2D array called final_report. Print it to the screen.

4. The NumPy Trap (Data Types): The administration suddenly wants you to add 5 bonus points to the scores in your final_report. Try to add 5 to one of the score columns. What happens? Print the .dtype (data type) of your final_report to figure out why.

5. The Export: Even though the math broke, save your final_report to your computer as a CSV file called "edupi_final_grades.csv" so another program can deal with it.

> Hint: np.savetxt("document_name.csv", <array>, delimiter=",", fmt="%s", header="ID,Sub1,Sub2,Sub3,Status")